[package]
name = "Staxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.1"
futures = "0.3.28"
iced = "0.10.0"
rdev = "0.5.3"




